analysis_system_web/configs/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),
]

analysis_system_web/events/urls.py
from django.urls import path
from django.shortcuts import redirect

from .views import *

urlpatterns = [
    path('error/', ErrorTemplateView.as_view(), name='error'),
    path('register-event/', EventCreateView.as_view(), name='register-event'),
    path('processed-result/<int:pk>/', ProcessedTemplateView.as_view(), name='processed-page'),
    path('', lambda req: redirect('/register-event/')),
]

analysis_system_web/events/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _



class Event(models.Model):
    title = models.CharField(_("Title"), max_length=50, null=False, blank=False)
    base_blood_pressure = models.PositiveIntegerField(_("Base Blood Pressure"), null=False, blank=False)
    base_heart_rate = models.PositiveIntegerField(_("Base Heart Rate"), null=False, blank=False)
    start_date = models.DateTimeField(_("Start Date"))
    end_date = models.DateTimeField(_("End Date"))
    is_fraud = models.BooleanField(_("Is Fraud ?"),  null=True)

    person = models.ForeignKey(to="persons.Person", on_delete=models.CASCADE, null=False)
    blood_pressure_monitor = models.ForeignKey(to="monitors.Monitor", related_name="blood_pressure_monitor", on_delete=models.CASCADE, null=False)
    heart_rate_monitor = models.ForeignKey(to="monitors.Monitor", related_name="heart_rate_monitor", on_delete=models.CASCADE, null=False)

    def __str__(self) -> str:
        fraud = ""
        if self.is_fraud is None:
            fraud = "Still Unknow"
        elif self.is_fraud is False:
            fraud = "No"
        else:
            fraud = "Yes"
        return f"{self.title} - Fraud: {fraud}"

analysis_system_web/evidences/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class BloodPressureEvidence(models.Model):
    systolic_bp = models.PositiveIntegerField(_("Systolic Blood Pressure"), null=False, blank=False)
    event = models.ForeignKey(to="events.Event", on_delete=models.CASCADE, null=False, blank=False)
    date = models.DateTimeField()

class HeartRateEvidence(models.Model):
    pulse = models.PositiveIntegerField(_("Pulse"), null=False, blank=False)
    event = models.ForeignKey(to="events.Event", on_delete=models.CASCADE, null=False, blank=False)
    date = models.DateTimeField()

analysis_system_web/monitors/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from monitors.choices import MONITOR_TYPE_CHOICES


class Monitor(models.Model):
    device = models.CharField(_("Device"), max_length=50, null=False, blank=False)
    version = models.CharField(_("Version"), max_length=50, null=False, blank=False)
    type = models.CharField(_("Version"), max_length=20, choices=MONITOR_TYPE_CHOICES)

    def __str__(self) -> str:
        return f"{self.device} / {self.version}"

analysis_system_web/persons/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Person(models.Model):
    name = models.CharField(_("Name"), max_length=50, null=False, blank=False)
    surname = models.CharField(_("Surname"), max_length=50, null=False, blank=False)
    age = models.PositiveIntegerField(_("Age"), null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.name} {self.surname}"

analysis_system_web/events/forms.py
from django import forms
from monitors.models import Monitor

from persons.models import Person
from events.models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['blood_pressure_monitor']=forms.ModelChoiceField(queryset=Monitor.objects.filter(type='BLOOD_PRESSURE'))
        self.fields['heart_rate_monitor']=forms.ModelChoiceField(queryset=Monitor.objects.filter(type='HEART_RATE'))
        self.fields['person']=forms.ModelChoiceField(queryset=Person.objects.all())

analysis_system_web/events/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView
from django.urls import reverse
from structlog import get_logger

from events.services import EventService
from events.forms import EventForm
from events.models import Event

event_service = EventService()
log = get_logger()


class EventCreateView(LoginRequiredMixin, CreateView):
    template_name = 'events/event_form.html'
    form_class = EventForm

    def form_valid(self, form):
        try:
            log.info("[Event View] Form valid...")
            record = form.save(commit=True)
            record.is_fraud, graph_data = event_service.process_integration(record)
            self.kwargs["new_id"] = record.id
            self.request.session["graph_data"] = graph_data
            return super().form_valid(record)
        except:
            log.info("[Event View] Redirecting to Error Page...")
            return HttpResponseRedirect(reverse('error'))

    def get_success_url(self, **kwargs):        
        return reverse('processed-page', kwargs={'pk': self.kwargs["new_id"]})


class ProcessedTemplateView(LoginRequiredMixin, DetailView):
    template_name = 'events/result.html'
    model = Event
    context_object_name = 'event'

    def get_context_data(self, **kwargs):
        log.info("[Event View] Puting graph data into context...")
        context = super().get_context_data(**kwargs)
        graph_data = self.request.session.pop("graph_data", {})
        context['bp_x'] = graph_data.get('bp_x', [])
        context['bp_y'] = graph_data.get('bp_y', [])
        context['hr_x'] = graph_data.get('hr_x', [])
        context['hr_y'] = graph_data.get('hr_y', [])
        return context

class ErrorTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'events/error.html'

analysis_system_web/events/templates/events/error.html
<script
  src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
  integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
  crossorigin="anonymous">
</script>

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Error Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <h3 class="mt-5 mb-3">Sorry...</h3>
            <h5>Service Unavaliable</h5>
                <div class="mt-3">
                    <p>
                        We are sorry to inform that this service is unavaliable at the moment.
                    </p>
                    <p>
                        But don't worry. We are working to make it available in some moments
                    </p>
                </div>
          </div>
        </div>
        <div class="row">
          <div class="d-grid col-sm-12 mt-5 mb-3">
            <a href="{% url 'register-event'%}"
              class="btn btn-outline-info">Try Again
            </a>
          </div>
        </div>
      <div>        
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  </body>
</html>

analysis_system_web/events/templates/events/event_form.html
<script
  src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
  integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
  crossorigin="anonymous">
</script>

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register Event Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>

    {% load widget_tweaks %}

    <div class="container">
        <div class="alert alert-light mt-3" role="alert">
            Events are only processed after click in "End"
        </div>
        <h1 class="mb-3">Event Register</h1>
        <form class="row g-3" method="post" id="form-form">
            {% csrf_token %}
            <div class="col-sm-12 col-md-6">
                <label for="id_title" class="form-label">Title</label>
                <input class="form-control" type="text" name="title" maxlength="50" required="" id="id_title">
            </div>
            <div class="col-sm-12 col-md-6">
                <label for="id_person" class="form-label">Person</label>
                {% render_field form.person class="form-select" name="person" %}
            </div>
            <div class="col-sm-12 col-md-6">
                <label for="id_base_blood_pressure" class="form-label">Base Blood Pressure</label> 
                <input class="form-control" type="number" name="base_blood_pressure" min="0" required="" id="id_base_blood_pressure">
            </div>
            <div class="col-sm-12 col-md-6">
                <label for="id_blood_pressure_monitor" class="form-label">Blood pressure monitor</label>
                {% render_field form.blood_pressure_monitor class="form-select" name="blood_pressure_monitor" %}
            </div>

            <div class="col-sm-12 col-md-6">
                <label for="id_base_heart_rate" class="form-label">Base Heart Rate</label>
                <input class="form-control" type="number" name="base_heart_rate" min="0" required="" id="id_base_heart_rate">
            </div>

            <div class="col-sm-12 col-md-6">
                <label for="id_heart_rate_monitor" class="form-label">Heart rate monitor</label>
                {% render_field form.heart_rate_monitor class="form-select" name="heart_rate_monitor" %}
            </div>

            <input type="hidden" name="start_date" min="0" id="id_start_date"> 
            <input type="hidden" name="end_date" min="0" id="id_end_date"> 

            <div class="d-grid gap-2 col-sm-12 col-md-6">
                <button id="start-button" type="button" class="btn btn-primary">Start</button>
            </div>
            <div class="d-grid gap-2 col-sm-12 col-md-6">
                <button id="end-button" type="submit" class="btn btn-secondary" disabled>End</button>
            </div>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script>
        function generateDatetime() {
            const dt = new Date();
            return dt.toISOString();
        }
        $("#start-button").click(function () {
            if (! $('#form-form')[0].checkValidity()) {
                $('#form-form')[0].reportValidity()
            } else {
                $('#start-button').prop('disabled', true)
                $('#id_title').prop('disabled', true)
                $('#id_person').prop('disabled', true)
                $('#id_base_blood_pressure').prop('disabled', true)
                $('#id_base_heart_rate').prop('disabled', true)
                $('#id_blood_pressure_monitor').prop('disabled', true)
                $('#id_heart_rate_monitor').prop('disabled', true)

                $("#id_start_date").val(generateDatetime());
                $('#end-button').prop('disabled', false)
            }

        });
        $("#form-form").on("submit", function(event) {
            $('#start-button').prop('disabled', true)

            $('#id_title').prop('disabled', false)
            $('#id_person').prop('disabled', false)
            $('#id_base_blood_pressure').prop('disabled', false)
            $('#id_base_heart_rate').prop('disabled', false)
            $('#id_blood_pressure_monitor').prop('disabled', false)
            $('#id_heart_rate_monitor').prop('disabled', false)

            $("#id_end_date").val(generateDatetime());
        });
    </script>
  </body>
</html>

analysis_system_web/events/templates/events/result.html
<script
  src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
  integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
  crossorigin="anonymous">
</script>

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Result Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <h3 class="mt-5 mb-3">{{event.person.name}} {{event.person.surname}}</h3>
            <h5>Fraud Analysis: {{event.is_fraud}}</h5>
            <p>
                <div>Event: {{event.title}}</div>
                <div>Base Blood Pressure: {{event.base_blood_pressure}}</div>
                <div>Base Heart Rate: {{event.base_heart_rate}}</div>
            </p>
                <div>Blood Pressure Monitor: {{event.blood_pressure_monitor.device}} / {{event.blood_pressure_monitor.version}}</div>
                <div>Heart Rate Monitor: {{event.heart_rate_monitor.device}} / {{event.heart_rate_monitor.version}}</div>
            </p>
          </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <canvas id="bpChart"></canvas>
            </div>
            <div class="col-sm-12 col-md-6">
                <canvas id="hrChart"></canvas>
            </div>
        </div>
        <div class="row">
          <div class="d-grid col-sm-12 mt-5 mb-3">
            <a href="{% url 'register-event'%}"
              class="btn btn-outline-info">Register New Fraud Test
            </a>
          </div>
        </div>
      <div>        
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>        
    <script>
      const bp_chart = document.getElementById('bpChart');
      const bp_label = '# Blood Pressure Measures'
      var bp_x = {{ bp_x|safe }};
      var bp_y = {{ bp_y|safe }};
      const bp_color = "rgba(160,208,246,1)";
      generateChart(bp_chart, bp_label, bp_x, bp_y, bp_color)

      const hr_chart = document.getElementById('hrChart');
      const hr_label = '# Heart Rate Measures'
      var hr_x = {{ hr_x|safe }};
      var hr_y = {{ hr_y|safe }};
      const hr_color = "rgba(255,128,128,0.8)";
      generateChart(hr_chart, hr_label, hr_x, hr_y, hr_color)

      function generateChart(chart, label, x_list, y_list, bg_rgb) {
        new Chart(chart, {
          type: 'bar',
          data: {
            labels: x_list,
            datasets: [{
              label: label,
              data: y_list,
              backgroundColor: bg_rgb,
              borderWidth: 1
            }]
          },
          options: {
            scales: {
              y: {
                beginAtZero: true
              }
            }
          }
        });
      }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  </body>
</html>